CREATE TABLE IF NOT EXISTS `tbl_user`(
  `pk_user_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_type` enum('company','personal','bid','admin') DEFAULT 'personal',
  `parent_company` int(11) NOT NULL DEFAULT '0',
  `user_level` enum('admin','normal') DEFAULT 'admin',
  `token` varchar(255) DEFAULT NULL,
  `first_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) DEFAULT NULL,
  `name` varchar(200) DEFAULT NULL,
  `username` varchar(100) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `password` varchar(200) NOT NULL,
  `headline` varchar(200) DEFAULT NULL,
  `summary` text,
  `profile_small` varchar(100) DEFAULT NULL,
  `profile_medium` varchar(100) DEFAULT NULL,
  `profile_large` varchar(100) DEFAULT NULL,
  `profile_cover` varchar(100) DEFAULT NULL,
  `profile_url` varchar(200) DEFAULT NULL,
  `mobile` varchar(100) DEFAULT NULL,
  `phone` varchar(100) DEFAULT NULL,
  `fax` varchar(100) DEFAULT NULL,
  `religion` varchar(100) DEFAULT NULL,
  `birthday` varchar(100) DEFAULT NULL,
  `gender` varchar(100) DEFAULT NULL,
  `marital` varchar(100) DEFAULT NULL,
  `id_number` varchar(100) DEFAULT NULL,
  `license_number` varchar(100) DEFAULT NULL,
  `website` varchar(100) DEFAULT NULL,
  `fk_country_id` int(11) DEFAULT '0',
  `fk_city_id` int(11) DEFAULT '0',
  `fk_area_id` int(11) DEFAULT '0',
  `postal_code` varchar(100) DEFAULT NULL,
  `address` text,
  `latitude` varchar(100) DEFAULT NULL,
  `longitude` varchar(100) DEFAULT NULL,
  `otp` varchar(100) DEFAULT NULL,
  `added_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `modified_date` datetime DEFAULT NULL,
  `flag` int(11) NOT NULL DEFAULT '0',
  `order_rank` int(11) NOT NULL DEFAULT '10',
  `is_app_user` int(11) DEFAULT '0',
  `verified` int(11) NOT NULL DEFAULT '0',
  `status` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`pk_user_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;